nodeday/nodeday.github.io

2015-condenast/index.html, index.html
Supersedes #14.
* Changed 'Travell is CTO at Fidelity' to 'Travell is a CTO at Fidelity'
* Updated bio for Mikeal Rogers
* Updated company name under Matthew Podwysocki's photo
=> Minor updates to speaker details

2015-condenast/index.html, index.html
Code of conduct copied from NodeConf EU website at Cian's request.
=> Added code of conduct

2015-condenast/index.html, index.html
Just changed the data. tito link still needs to be changed.
=> Changed date from 27 to 28 and Clifton's bio fixes

2015-condenast/index.html, index.html
Hi @totherik. I've done some changes to the schedule time intervals. I'll have another PR later today with some changes to the talk titles.
Thanks.
=> updated schedule time intervals

2015-condenast/index.html, index.html
=> Changed Lin Clark's talk title

index.html
Thanks for spotting this @rfeathers.
=> replaced location links

2015-digitas/css/app.css, 2015-digitas/index.html, index.html
@rfeathers Hi Ron, I'm Mike - the front end developer intern at nearForm and I'll be in charge of the website and will be making all changes to it. It's great to meet you.
=> added initial speakers

CNAME
Hi @rfeathers. I've heard www.nodeday.com is not resolving in the browser, just nodeday.com, so this might help.
=> changed domain name in CNAME

CNAME
Reverts nodeday/nodeday.github.io#35
=> Revert "changed domain name in CNAME"

2015-digitas/index.html, index.html
@rfeathers the bio's got mixed up, this PR is just to rectify this.
=> The two Ian's bio's got mixed up

2015-digitas/index.html, index.html
fixed spelling mistakes along with other small fixes and changes @rfeathers
=> added back in the about section

2015-digitas/index.html, index.html
hopefully this is the last of the changes @rfeathers
=> made changes to the agenda and fixed some other small typo's.

2015-icemobile/css/app.css, index.html
* makes "register" link more visible
* adds map to address
* changes company name
=> small improvements

2016-icemobile/index.html, index.html
and updates archived version to latest state
=> fixes date in title

.gitignore, 2015-digitas/index.html, 2015-paypal-intuit/index.html, 2016-icemobile/css/app.css
* adds registration link to navbar
* adds registration link below logos
* makes "previous nodeday" links work correctly
* updates gitignore
=> updates styling

2018-nearform/index.html
A few extra lines of text about the hotel options
=> Adding extra hotel info

2018-nearform/index.html
Small link change - confirmed with Cliona so I'll go ahead and merge
=> Updating Tito link

2018-nearform/index.html
=> Updating spelling

2018-nearform/index.html
=> fix(typo): Fix about NodeDay - node.js description

2018-nearform/index.html
given the context of panelists change and industry interest in facebook and privacy, it warrants to call out "privacy" as part of the conversation
=> Panel topic tweak
